routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::post('xsolla' , 'WebHookController@index')->name('xsolla');


Route::get('/about', function () {
    return view('about');
})->name('about');
Route::get('/privacy', function () {
    return view('privacy');
})->name('privacy');
Route::get('/terms', function () {
    return view('terms');
})->name('terms');
Route::get('/', function () {
    return view('welcome');
})->name('welcome');

Route::get('/cards', function () {
    return view('cards_example');
});


Route::get('/purchase', 'TransactionController@show')->name('payment');


Route::get('/faq', function () {
    return view('faq');
})->name('faq');
Route::get('/verification',function(){
   return view('verification');
})->name('remove.deposit')->middleware(\App\Http\Middleware\Authenticate::class);
Auth::routes();

Route::prefix('user')->group(function () {
    Route::get('/', 'UserController@profile')->name('profile');
    Route::get('/inventory/cards', 'UserController@cards')->name('home')->middleware(\App\Http\Middleware\ClearCache::class);
    Route::get('/inventory/packs', 'UserController@packs')->name('user.packs')->middleware(\App\Http\Middleware\ClearCache::class);
    Route::get('/inventory/open', function () {
        return view('inventory');
    })->middleware(\App\Http\Middleware\ClearCache::class);
    Route::post('/inventory/open', 'OpenController@index')->middleware(\App\Http\Middleware\ClearCache::class)->name('user.open');
    Route::post('/inventory/sell', 'SellController@sell')->name('user.sell');
    Route::post('/inventory/quicksell', 'SellController@quickSell')->name('user.quickSell');
    Route::get('/inventory/withdraw', 'WithdrawController@index')->name('user.withdraw');
    Route::get('/transactions', 'UserController@transactions')->name('user.transactions');
    Route::get('/withdraws', 'UserController@withdraws')->name('user.withdraws');
    Route::post('/inventory/withdraw', 'WithdrawController@withdraw')->name('user.post.withdraw');
    Route::post('/updateInfo', 'UserController@updateInfo')->name('user.update');
});

Route::post('/lastTransactions', 'UserController@lastTransactions');

Route::get('/users/logout', 'Auth\LoginController@userLogout')->name('user.logout');
Route::post('/cardinfo', 'PlayerInfoController@getInfo');
Route::post('/manycardsinfo', 'PlayerInfoController@getInfoPlayers');


Route::prefix('packs')->group(function () {
    Route::get('/display/{id}', 'MarketPlaceController@display')->name('packs.displaySingle');
    Route::get('/', 'MarketPlaceController@index')->name('packs.marketplace');
    Route::get('/custom','MarketPlaceController@customPacks')->name('packs.custom.marketplace');
    Route::post('/buy', 'BuyController@buy')->name('packs.purchase');
    Route::get('/buy', function () {
        return redirect()->back();
    });
    Route::get('/create', 'CreatePackController@pack')->name('pack');
    Route::get('/create/{num}', 'CreatePackController@packSize')->name('pack.chooseCards');
    Route::post('/create/{num}/probability', 'CreatePackController@probabilityCards')->name('pack.probability');
    Route::get('/create/{num}/probability', 'CreatePackController@wrongProbabilities')->name('pack.get.probability');
    Route::post('/create/{num}/overview', 'CreatePackController@overviewPack')->name('pack.overview');
    Route::post('/create/submit/{num}', 'CreatePackController@store')->name('pack.store');
    Route::get('/console', 'MarketPlaceController@console')->name('pack.console');
});
Route::prefix('admin')->group(function () {
    Route::get('/login', 'Auth\AdminLoginController@loginForm')->name('admin.login');
    Route::post('/login', 'Auth\AdminLoginController@login')->name('admin.login.submit');
    Route::get('/', 'Admin\AdminController@index')->name('admin.dashboard');
    Route::get('/logout', 'Auth\AdminLoginController@logout')->name('admin.logout');

    //Routes for transactions
    Route::get('/transactions', 'Admin\AdminTransactionController@getTransactions')->name('admin.transactions');
    Route::get('/transaction/{id}', 'Admin\AdminTransactionController@getTransactionById')->name('admin.transaction');
    Route::post('/transaction/add/note', 'Admin\AdminTransactionController@addNote');
    Route::get('/transaction/add/note', function () {
        return redirect()->back();
    });

    //Routes for withdraws
    Route::get('/withdraws', 'Admin\AdminWithdrawController@getWithdraws')->name('admin.withdraws');
    Route::get('/withdraw/{id}', 'Admin\AdminWithdrawController@getWithdrawById')->name('admin.withdraw');
    Route::post('/withdraw/manage', 'Admin\AdminWithdrawController@handleWithdraw');
    Route::get('/withdraw/manage', function () {
        return redirect()->back();
    });
    Route::post('/withdraw/add/note', 'Admin\AdminWithdrawController@addNote');
    Route::get('/withdraw/add/note', function () {
        return redirect()->back();
    });

    //Routes for admin
    Route::get('/form', 'Admin\AdminController@adminForm')->name('admin.form');
    Route::post('/create', 'Admin\AdminController@createAdmin');
    Route::get('/create', function () {
        return redirect()->back();
    });
    Route::get('/list', 'Admin\AdminController@displayAdmins')->name('admin.list');
    Route::get('/users', 'Admin\AdminUserController@displayUsers')->name('admin.users');
    Route::get('/users/{id}', 'Admin\AdminUserController@getUserById')->name('admin.user');
    Route::post('/users/modify', 'Admin\AdminUserController@modifyUserStatus');
    Route::get('/users/modify', function () {
        return redirect()->back();
    });
    Route::post('/users/add/note', 'Admin\AdminUserController@addNote');
    Route::get('/users/add/note', function () {
        return redirect()->back();
    });

    //Routes for packs
    Route::get('/pack', 'Admin\CardPackController@displayPacks')->name('admin.displaypacks');
    Route::get('/pack/view/{id}', 'Admin\CardPackController@singlePackView')->name('admin.packview');
    Route::get('/pack/form', 'Admin\CardPackController@packForm')->name('admin.createpack');
    Route::post('/pack/create', 'Admin\CardPackController@createPack');
    Route::get('/pack/create', function () {
        return redirect()->back();
    });
    Route::post('/pack/search', 'Admin\CardPackController@packFind');
    Route::get('/pack/search', function () {
        return redirect()->back();
    });
    Route::post('/pack/modify', 'Admin\CardPackController@modifyPack');
    Route::get('/pack/modify', function () {
        return redirect()->back();
    });

    //Routes for cards
    Route::get('/card', 'Admin\CardPackController@displayCards')->name('admin.displaycard');
    Route::get('/card/form', 'Admin\CardPackController@cardForm')->name('admin.createcard');
    Route::get('/card/create', function () {
        return redirect()->back();
    });
    Route::post('/card/create', 'Admin\CardPackController@createCard');
    Route::post('/card/update', 'Admin\CardPackController@updateCardPrice');
    Route::get('/card/update', function () {
        return redirect()->back();
    });

    //Routes to reset Passwords
    Route::post('/password/email', 'Auth\AdminForgotPasswordController@sendResetLinkEmail')->name('admin.password.email');
    Route::get('/password/reset', 'Auth\AdminForgotPasswordController@showLinkRequestForm')->name('admin.password.request');
    Route::post('/password/reset', 'Auth\AdminResetPasswordController@reset');
    Route::get('/password/reset/{token}', 'Auth\AdminResetPasswordController@showResetForm')->name('admin.password.reset');
});


Route::prefix('search')->group(function () {
    Route::get('/cards', 'CardSearchController@search')->name('search.card');
    Route::get('/packs', 'PackSearchController@search')->name('search.pack');
});

Route::post('/contact', 'ContactMessageController@store')->name('contact.message');

Route::post('/paypalPayement', 'TransactionController@insertTransaction')->name('payment.paypal');

app/Note.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Note extends Model
{
    protected $fillable =['transaction_id', 'admin_id', 'note', 'withdraw_id', 'user_id'];
    protected $table = 'notes';


    public function admin(){
        return $this->belongsTo(Admin::class);
    }

    public function transaction(){
        return $this->belongsTo(Transaction::class);
    }

    public function withdraw()
    {
        return $this->belongsTo(Withdraw::class);
    }

    public function getCreatedAtAttribute($date)
    {
        return \Carbon\Carbon::parse($date)->timezone('America/Toronto');
    }
}

resources/views/test.blade.php
<html>
<head lang="en">
    <meta charset="UTF-8">

</head>
<body>
<?php
use Xsolla\SDK\API\XsollaClient;
use Xsolla\SDK\API\PaymentUI\TokenRequest;

$tokenRequest = new TokenRequest((int)env('PROJECT_ID'), '1');
$tokenRequest
    ->setSandboxMode(true);

$xsollaClient = XsollaClient::factory(array(
    'merchant_id' => (int)env('MERCHANT_ID'),
    'api_key' => env('API_KEY')
));
$response = $xsollaClient->ListPaymentAccounts(array(
    'project_id' =>(int)env('PROJECT_ID'),
    'user_id' => '1'
));
$token = $xsollaClient->createPaymentUITokenFromRequest($tokenRequest);
echo $token;
\Xsolla\SDK\API\PaymentUI\PaymentUIScriptRenderer::send($token, $isSandbox = true)
?>

<button data-xpaystation-widget-open>Buy Credits</button>
<?php \Xsolla\SDK\API\PaymentUI\PaymentUIScriptRenderer::send($token, $isSandbox = true); ?>

</body>
</html>

resources/views/transactions.blade.php
<html xmlns="http://www.w3.org/1999/html">
<head>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css"
          integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">

    <title>HUTWINNER</title>
    <meta name="description" content="">
    <meta name="keywords" content="">
    <!-- STYLES -->
    <!-- OG meta tags that improve the look of your post on social media -->
    <meta property="og:site_name" content=""/><!--website name-->
    <meta property="og:site" content=""/> <!--website link-->
    <meta property="og:title" content=""/> <!--Post title-->
    <meta property="og:description" content=""/> <!--Post description-->
    <meta property="og:image" content=""/><!-- Image link (jpg only)-->
    <meta property="og:url" content=""/> <!--where do you want your post to link to-->
    <meta property="og:type" content="article"/>
    <link rel="apple-touch-icon" sizes="57x57" href="images/favicon/apple-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="images/favicon/apple-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="images/favicon/apple-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="images/favicon/apple-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="images/favicon/apple-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="images/favicon/apple-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="images/favicon/apple-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="images/favicon/apple-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="images/favicon/apple-icon-180x180.png">
    <link rel="icon" type="image/png" sizes="192x192"  href="images/favicon/android-icon-192x192.png">
    <link rel="icon" type="image/png" sizes="32x32" href="images/favicon/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="96x96" href="images/favicon/favicon-96x96.png">
    <link rel="icon" type="image/png" sizes="16x16" href="images/favicon/favicon-16x16.png">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
    <meta name="theme-color" content="#ffffff">


    <link rel="stylesheet" href="{{ asset('css/packDisplay.css') }}">
    <link href="{{ asset('css/style.css') }}" rel="stylesheet">
    <link rel="stylesheet" href="{{asset('css/nav.css')}}">
    <link href="/css/font-awesome.min.css" rel="stylesheet">
    <script src="https://cdn.rawgit.com/webcomponents/webcomponentsjs/v0.7.24/webcomponents-lite.js"></script>
    <style>
        @import url(https://fonts.googleapis.com/css?family=Roboto:400,500,700);
        @import url(https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic);

        .navbar, #footer {
            background: #20202A !important;
        }

        .buttonValue {
            background: #F6EA9C !important;
            color: #000 !important;
        }

        .table td {
            border-top: 1px solid #F6EA9C !important;;
        }

        .table thead th {
            border-bottom: unset !important;
        }

        @media (min-width: 1200px) {
            .container {
                max-width: 90%;
            }
        }

        input, select {
            background: rgba(0, 0, 0, 0.5) !important;
            color: white !important;
            border: 1px solid #F6EA9C !important;
        }

        .tableContainer {
            background: #30303F !important;
            border-radius: 15px 15px 15px 15px;
            -webkit-box-shadow: 0 30px 30px 0 rgba(0, 0, 0, 0.3);
            box-shadow: 0 30px 30px 0 rgba(0, 0, 0, 0.3);
            margin-bottom: 8%;
            overflow-y: scroll;
        }

        .table th {
            border-top: unset !important;
        }

        .main-container {
            background: #363647 !important;
            border-radius: 15px 15px 15px 15px;
            -webkit-box-shadow: 0 30px 30px 0 rgba(0, 0, 0, 0.3);
            box-shadow: 0 30px 30px 0 rgba(0, 0, 0, 0.3);
            margin-bottom: 120px !important;
        }

        @media (min-width: 1200px) {
            .container {
                max-width: 85%;
            }
        }

        .columnValue {
            min-height: 342px;
            min-width: 242px;
            padding: unset;
        }


    </style>
    <link href="/css/floatingSupport.css" rel="stylesheet">
</head>
<body style="position:relative; background: #202033 !important;">
<header id="main-header">
    @component('components.nav',['header'=> 'Profile', 'coloredHeader' => ''])
    @endcomponent
</header>
<div id="container">
    <div class="main-container container pt-5 mt-3">
        <div class="row">
            <div class="col-12">
                <h2 class="marketPlaceTitle headerMarketplace animation-element slide-down text-center"><span
                            class="colored">TRANSACTIONS</span></h2>
            </div>
        </div>
        <div class="row">
            <div class="container">
                <div class="row justify-content-center">
                    @if( $transactions->isEmpty())
                        <h3>
                            You have yet to buy any coins
                            Got to the <a href="{{ route('payment') }}" style="color: #b48445;">Payment page</a> and buy
                            coins!.
                        </h3>
                    @else
                        <table class="table tableContainer h-50" style="">
                            <thead>
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col">Points</th>
                                <th scope="col">Price</th>
                                <th scope="col">Time</th>
                                <th scope="col">Payment Method</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($transactions as $transaction)
                                <tr>
                                    <td>
                                        {{ $transaction->id }}
                                    </td>
                                    <td>
                                        {{ $transaction->points }}
                                    </td>
                                    <td>
                                        {{ $transaction->price }}
                                    </td>
                                    <td>
                                        {{ $transaction->created_at->toDateString() }}
                                    </td>
                                    <td>
                                        {{ $transaction->payment_method()->first()->method }}
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    @endif
                </div>
            </div>
        </div>
    </div>
    @component('components.support')
    @endcomponent
    @component('components.footer')
    @endcomponent
</div>
<script src="/js/jquery-3.2.1.min.js"></script>
<script src="/js/floatingSupport.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
<script src="https://twitter.github.io/typeahead.js/releases/latest/typeahead.bundle.js"></script>
</body>
</html>

resources/views/withdraws.blade.php
<html xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <title>HUTWINNER</title>
    <meta name="description" content="">
    <meta name="keywords" content="">
    <!-- OG meta tags that improve the look of your post on social media -->
    <meta property="og:site_name" content=""/><!--website name-->
    <meta property="og:site" content=""/> <!--website link-->
    <meta property="og:title" content=""/> <!--Post title-->
    <meta property="og:description" content=""/> <!--Post description-->
    <meta property="og:image" content=""/><!-- Image link (jpg only)-->
    <meta property="og:url" content=""/> <!--where do you want your post to link to-->
    <meta property="og:type" content="article"/>
    <link rel="apple-touch-icon" sizes="57x57" href="images/favicon/apple-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="images/favicon/apple-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="images/favicon/apple-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="images/favicon/apple-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="images/favicon/apple-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="images/favicon/apple-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="images/favicon/apple-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="images/favicon/apple-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="images/favicon/apple-icon-180x180.png">
    <link rel="icon" type="image/png" sizes="192x192"  href="images/favicon/android-icon-192x192.png">
    <link rel="icon" type="image/png" sizes="32x32" href="images/favicon/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="96x96" href="images/favicon/favicon-96x96.png">
    <link rel="icon" type="image/png" sizes="16x16" href="images/favicon/favicon-16x16.png">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
    <meta name="theme-color" content="#ffffff">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css"
          integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">


    <!-- STYLES -->

    <link rel="stylesheet" href="{{ asset('css/packDisplay.css') }}">
    <link href="{{ asset('css/style.css') }}" rel="stylesheet">
    <link rel="stylesheet" href="{{ asset('css/nav.css')}}">

    <link href="/css/font-awesome.min.css" rel="stylesheet">
    <script src="https://cdn.rawgit.com/webcomponents/webcomponentsjs/v0.7.24/webcomponents-lite.js"></script>
    <style>
        @import url(https://fonts.googleapis.com/css?family=Roboto:400,500,700);
        @import url(https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic);

        .navbar, #footer {
            background: #20202A !important;
        }

        .buttonValue {
            background: #F6EA9C !important;
            color: #000 !important;
        }



        .table td {
            border-top: 1px solid #F6EA9C !important;;
        }

        .table thead th {
            border-bottom: unset !important;
        }

        @media (min-width: 1200px) {
            .container {
                max-width: 90%;
            }
        }

        input, select {
            background: rgba(0, 0, 0, 0.5) !important;
            color: white !important;
            border: 1px solid #F6EA9C !important;
        }

        .tableContainer {
            background: #30303F !important;
            border-radius: 15px 15px 15px 15px;
            -webkit-box-shadow: 0 30px 30px 0 rgba(0, 0, 0, 0.3);
            box-shadow: 0 30px 30px 0 rgba(0, 0, 0, 0.3);
            margin-bottom: 8%;
            overflow-y: scroll;
        }

        .table th {
            border-top: unset !important;
        }

        .main-container {
            background: #363647 !important;
            border-radius: 15px 15px 15px 15px;
            -webkit-box-shadow: 0 30px 30px 0 rgba(0, 0, 0, 0.3);
            box-shadow: 0 30px 30px 0 rgba(0, 0, 0, 0.3);
            margin-bottom: 120px !important;
        }

        @media (min-width: 1200px) {
            .container {
                max-width: 85%;
            }
        }

        .columnValue {
            min-height: 342px;
            min-width: 242px;
            padding: unset;
        }


    </style>
    <link href="/css/floatingSupport.css" rel="stylesheet">
</head>
<body style="position:relative; background: #202033 !important;">
<header id="main-header">
    @component('components.nav',['header'=> 'Profile', 'coloredHeader' => ''])
    @endcomponent
</header>
<div id="container">
<div class="main-container container pt-5 mt-3">
    <div class="row">
        <div class="col-12">
            <h2 class="marketPlaceTitle headerMarketplace animation-element slide-down text-center"><span
                        class="colored">Withdraw Request</span></h2>
        </div>
    </div>
    <div class="row">
        <div class="container">
            <div class="row justify-content-center">
                @if( $withdraws->isEmpty())
                    <h3>
                        You have yet to withdraw any cards.
                        Go to the <a href="{{ route('user.withdraw') }}" style="color: #b48445;">Withdraw page</a> and
                        make a request.
                    </h3>
                @else
                    <table class="table tableContainer h-50" style="">
                        <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Status</th>
                            <th scope="col">Number of Cards</th>
                            <th scope="col">Time</th>
                            <th scope="col">Cards Request</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($withdraws as $withdraw)
                            <tr>
                                <td>
                                    {{ $withdraw->id }}
                                </td>
                                <td>
                                    <?php
                                    $val = $withdraw->status->first()->type;
                                    ?>
                                    @if($val =='Pending')
                                        <span class="colored">{{ $val }}</span>
                                    @elseif($val == 'Accepted')
                                        <span class="text-success">{{ $val }}</span>
                                    @else
                                        <span class="text-danger">{{ $val }}</span>
                                    @endif
                                </td>
                                <td>
                                    {{ count($withdraw->cards()->get()) }}
                                </td>
                                <td>
                                    {{ $withdraw->created_at }}
                                </td>
                                <td>

                                    @foreach($withdraw->cards()->get() as $card)
                                        <ul>
                                            <li>
                                                Player: {{$card->player_name}}
                                            </li>
                                            <li>
                                                Overall: {{$card->overall}}
                                            </li>
                                            <li>
                                                Type: {{ $card->cardType()->first()->type }}
                                            </li>
                                            <li>
                                                Synergy: {{ $card->synergy }}
                                            </li>
                                        </ul>
                                    @endforeach
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                @endif
            </div>
        </div>
    </div>
</div>
    @component('components.support')
    @endcomponent
@component('components.footer')
@endcomponent
</div>
<script src="/js/jquery-3.2.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
<script src="https://twitter.github.io/typeahead.js/releases/latest/typeahead.bundle.js"></script>
<script src="/js/floatingSupport.js"></script>
</body>
</html>